### ISSUE TITLE
Training on Multi-View RGB-D Data and Testing on Single-View RGB-D

### ISSUE THREAD

**Issue by GuanxingLu** [ShunyuanZheng/GPS-Gaussian#10]
Hi there! I'm impressed with your work and had a question about the possibility of training a model on multi-view RGB-D data and then testing it on single-view RGB-D data. This scenario is particularly useful when training in a simulation environment and deploying the model in the real world.

I would greatly appreciate any insights or guidance on how to proceed with this. Thank you for your time and assistance!

**Comment by ShunyuanZheng** [comment]
Hi, 

I think when using RGB-D data as input, it becomes a task of extrapolation rather than an interpolation problem under a stereo camera setting. If there is slight self-occlusion, I think it can synthesize high-quality novel views under a limited pitch & roll. However, if severe self-occlusion exists, I think you need an auxiliary network to complement the incomplete Gaussian points or an inpainting network to do it on 2D novel view outputs.
