### ISSUE TITLE
Question abount training on 8 camera setting.

### ISSUE THREAD

**Issue by CVStack** [ShunyuanZheng/GPS-Gaussian#14]
Thank you for sharing the code and pre-processed dataset.

They are very helpful for my research.

But i have the question about training on 8 camera setting.

I got the pre-processed dataset from here and merged two views (camera) folder into a folder for converting dataset of 16 views  into 8 views. 
(ex> 0004_000, 0004_001 (16 views) --> 0004_000 (8 views) 
But the result was bad when using the dataset of 8 view. (Especially, depth estimation module (stage 1)) 

Is there something to do when merging the folder?

Thank you.

**Comment by ShunyuanZheng** [comment]
Thank you for your interest! The dataset in Netdisk is under 16-camera setting, and it can not be directly converted to 8-camera setting via merging two cameras, since each folder refers to a specific training sample, where ```0.jpg``` and ```1.jpg``` are source views and the others are novel views. I recommend rendering 8-camera training data of THuman2.0 using the [render_data.py](https://github.com/ShunyuanZheng/GPS-Gaussian/blob/main/prepare_data/render_data.py).

**Comment by CVStack** [comment]
Okay. Thank you!
